### ISSUE TITLE
commonjs-dependencies

### ISSUE THREAD

**Issue by Jamforce** [tylerhubert/rsql-criteria-typescript#16]
Hi,

When using togheter with Angular 10, I get this WARNING in console

WARNING in ...\node_modules\rsql-criteria-typescript\dist\lib\index.js depends on 'util'. CommonJS or AMD dependencies can cause optimization bailouts.

From https://angular.io/guide/build#configuring-commonjs-dependencies:
It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application. For more information, see How CommonJS is making your bundles larger.

**Comment by tylerhubert** [comment]
Hello!

Thank you for the report.  Can you please let me know which version of the library you are on?  

A few weeks ago we committed some updates that would hopefully modernize and get rid of these warnings.  I've gotten busy with work and haven't been able to fully verify if all of the warnings have disappeared on the latest 2.3.0 version though.

If you are on the latest version and still seeing this error, then I can continue looking into seeing if there is an updated version of `util` or if I need to use something else.  Currently using it to know if an input is a number or not iirc.

Thank you!

**Comment by Jamforce** [comment]
Thank you for the quick response, Im on the latest version

**Comment by tylerhubert** [comment]
@Jamforce, sorry for the long delay in fixing this, but code was just merged to fix this.

Version 2.3.1 has been published to NPM:  https://www.npmjs.com/package/rsql-criteria-typescript

**Comment by tylerhubert** [comment]
Closing this issue as the reliance on node's `util` package has been removed from the codebase.
